# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Ting\Downloads\PyQT\PyQT--master\test.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CamShow(object):
    def setupUi(self, CamShow):
        CamShow.setObjectName("CamShow")
        CamShow.resize(1026, 719)
        CamShow.setMinimumSize(QtCore.QSize(1026, 0))
        CamShow.setMaximumSize(QtCore.QSize(1026, 786))
        self.centralwidget = QtWidgets.QWidget(CamShow)
        self.centralwidget.setObjectName("centralwidget")
        self.ROIFm = QtWidgets.QFrame(self.centralwidget)
        self.ROIFm.setGeometry(QtCore.QRect(20, 410, 521, 251))
        self.ROIFm.setFrameShape(QtWidgets.QFrame.Box)
        self.ROIFm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ROIFm.setObjectName("ROIFm")
        self.label_2 = QtWidgets.QLabel(self.ROIFm)
        self.label_2.setGeometry(QtCore.QRect(60, 50, 351, 161))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(self.ROIFm)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 91, 21))
        self.label_7.setStyleSheet("font: 12pt \"Calibri\";")
        self.label_7.setObjectName("label_7")
        self.FullFm = QtWidgets.QFrame(self.centralwidget)
        self.FullFm.setGeometry(QtCore.QRect(20, 10, 521, 381))
        self.FullFm.setStyleSheet("font: 12pt \"Calibri\";")
        self.FullFm.setFrameShape(QtWidgets.QFrame.Box)
        self.FullFm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FullFm.setObjectName("FullFm")
        self.ShowBt = QtWidgets.QPushButton(self.FullFm)
        self.ShowBt.setGeometry(QtCore.QRect(130, 20, 71, 28))
        self.ShowBt.setObjectName("ShowBt")
        self.StopBt = QtWidgets.QPushButton(self.FullFm)
        self.StopBt.setGeometry(QtCore.QRect(210, 20, 111, 28))
        self.StopBt.setObjectName("StopBt")
        self.RecordBt = QtWidgets.QPushButton(self.FullFm)
        self.RecordBt.setGeometry(QtCore.QRect(330, 20, 101, 28))
        self.RecordBt.setObjectName("RecordBt")
        self.DispLb = QtWidgets.QLabel(self.FullFm)
        self.DispLb.setGeometry(QtCore.QRect(50, 90, 411, 261))
        self.DispLb.setText("")
        self.DispLb.setObjectName("DispLb")
        self.FilePathLE = QtWidgets.QLineEdit(self.FullFm)
        self.FilePathLE.setGeometry(QtCore.QRect(80, 50, 371, 31))
        self.FilePathLE.setText("")
        self.FilePathLE.setReadOnly(True)
        self.FilePathLE.setObjectName("FilePathLE")
        self.label_4 = QtWidgets.QLabel(self.FullFm)
        self.label_4.setGeometry(QtCore.QRect(30, 50, 51, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.FullFm)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 121, 20))
        self.label_5.setObjectName("label_5")
        self.FilePathBt = QtWidgets.QToolButton(self.FullFm)
        self.FilePathBt.setGeometry(QtCore.QRect(460, 50, 51, 31))
        self.FilePathBt.setObjectName("FilePathBt")
        self.ExitBt = QtWidgets.QPushButton(self.FullFm)
        self.ExitBt.setGeometry(QtCore.QRect(440, 20, 71, 28))
        self.ExitBt.setObjectName("ExitBt")
        self.AvgPlot = PlotWidget(self.centralwidget)
        self.AvgPlot.setGeometry(QtCore.QRect(550, 410, 461, 251))
        self.AvgPlot.setObjectName("AvgPlot")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(550, 380, 111, 31))
        self.label_8.setStyleSheet("font: 12pt \"Calibri\";")
        self.label_8.setObjectName("label_8")
        self.btnUpdate = QtWidgets.QPushButton(self.centralwidget)
        self.btnUpdate.setGeometry(QtCore.QRect(660, 390, 91, 21))
        self.btnUpdate.setObjectName("btnUpdate")
        CamShow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CamShow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1026, 21))
        self.menubar.setObjectName("menubar")
        CamShow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CamShow)
        self.statusbar.setObjectName("statusbar")
        CamShow.setStatusBar(self.statusbar)

        self.retranslateUi(CamShow)
        QtCore.QMetaObject.connectSlotsByName(CamShow)

    def retranslateUi(self, CamShow):
        _translate = QtCore.QCoreApplication.translate
        CamShow.setWindowTitle(_translate("CamShow", "CamShow"))
        self.label_7.setText(_translate("CamShow", "ROI 影像"))
        self.ShowBt.setText(_translate("CamShow", "Start"))
        self.StopBt.setText(_translate("CamShow", "Stop"))
        self.RecordBt.setText(_translate("CamShow", "Save"))
        self.label_4.setText(_translate("CamShow", "路徑:"))
        self.label_5.setText(_translate("CamShow", "及時全影像"))
        self.FilePathBt.setToolTip(_translate("CamShow", "<html><head/><body><p align=\"center\">...</p><p align=\"center\"><br/></p></body></html>"))
        self.FilePathBt.setText(_translate("CamShow", "..."))
        self.ExitBt.setText(_translate("CamShow", "Exit"))
        self.label_8.setText(_translate("CamShow", "垂直強度影像"))
        self.btnUpdate.setText(_translate("CamShow", "Update Wave"))
from pyqtgraph import PlotWidget
